### ISSUE TITLE
Auto generating agent ID

### ISSUE THREAD

**Issue by mspeich-sirius** [IBM-UrbanCode/UCD-Docker-Images#10]
Is there any way to change the startAgent.sh script so that it doesn't auto generate an ID on startup? This makes it impossible to persist the UCD configuration if the containers are restarted. Maybe define an environment variable that will be used instead. If the environment variable isn't specified, the behavior will be the same as it is currently.

For example:
echo "locked/agent.id=$AGENT_ID" >> /opt/ibm-ucd/agent/conf/agent/installed.properties

**Comment by nhmathis** [comment]
Hi @mspeich-sirius,

This issue is being resolved with pull request #11!

-Nick

**Comment by nhmathis** [comment]
Today [DockerHub UCD v6.2.5.2.929926 images](https://hub.docker.com/r/ibmcom/ucds) have been released and PR #11 has been merged. Now you can specify an AGENT_NAME environment variable to persist agents between `docker` starts and stops.
