### ISSUE TITLE
Images tagged with docker and windows have no additional plugins

### ISSUE THREAD

**Issue by mkorejo** [IBM-UrbanCode/UCD-Docker-Images#8]
I ran the image with the docker tag:
`docker run -d -p 8443:8443 -p 8080:8080 ibmcom/ucds:docker`

Server startup logs indicate 15 staged (automation) plugins and 12 staged source plugins. No plugins for Docker are installed.

I ran the image with the windows tag on a different Docker engine:
`docker run -d -p 443:8443 -p 80:8080 ibmcom/ucds:windows`

Logs indicate the same number of plugins are installed and no plugins for Windows.

**Comment by adamkingit** [comment]
The Dockerfile that builds the Docker derivative is here https://github.com/IBM-UrbanCode/UCD-Docker-Images/blob/master/deploy/ga/plugins/docker/Dockerfile
You see a reason the plugins wouldn't load?

**Comment by garrettux** [comment]
i know this is a fairly old issue, but I ran into the same thing, so commenting here for anyone else that has this issue.  I had to download the plugin zip files to `/opt/ibm-ucd/server/appdata/` instead of `/tmp/appdata` in order to have them load at startup.  An example from my working `Dockerfile`:

```
RUN apt-get -q update && \
  apt-get -q install -y curl git && \
  curl -s -o /opt/ibm-ucd/server/appdata/var/plugins/command/stage/mesos-marathon-3.869088.zip "https://public.dhe.ibm.com/software/products/UrbanCode/plugins/ibmucd/mesos-marathon/mesos-marathon-3.869088.zip" && \
  curl -s -o /opt/ibm-ucd/server/appdata/var/plugins/source/stage/DockerSourceConfig-17.905484.zip "https://public.dhe.ibm.com/software/products/UrbanCode/plugins/ibmucd/DockerSourceConfig/DockerSourceConfig-17.905484.zip" && \
  curl -s -o /opt/ibm-ucd/server/appdata/var/plugins/command/stage/docker-plugin-5.867460.zip "https://public.dhe.ibm.com/software/products/UrbanCode/plugins/ibmucd/docker-plugin/docker-plugin-5.867460.zip"
```
